# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c1324aefeb49400613c9ec4071e37d7d56c281e47cd9c87aa7b9014ec756b6f21703e7046ae53069f280b9b343bca6caa714f6a57bd11e6fc432f52e2525d5

test:
  secret_key_base: 2a36e10bbf17bf0db8e2a701ebbe4652de94f7140a5abe3f357638506bd19b9a7f005e14dab8a692a9a020fc9fb377c68a70844664ce65a99ab5c315e29617c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
